### ISSUE TITLE
Solution for Lab is Missing

### ISSUE THREAD

**Issue by meg-gutshall** [learn-co-students/array-methods-lab-v-000#1506]
Hello,

I noticed the solutions for this lab is missing. I submitted a pull request to add my solution to the Learn.co solution branch if you want to take a look.

Take care,
Meg Gutshall

**Comment by drakeltheryuujin** [comment]
Hi @meg-gutshall,

When submitting a PR, the `learn-co-curriculum` repositories are reserved for
proposed edits and improvements to the curriculum that will update across all
forks. 

We have updated the materials and believe the issue to have been resolved. 

As always, thanks for contributing! 💙
